### PR TITLE
Add search box

### PR DESCRIPTION
**Pull request by nt1m**
This adds a basic search box functionality.

### CODE REVIEW

**Comment by captainbrosset** [comment]
This new search box looks great! Very useful. Thanks.
Can you rebase your branch on top of my latest master though?
Also, not a big deal for now, but it'd be great if you could squash all your PR commits into 1 final commit before opening the PR.
Thanks Tim!

**Comment by nt1m** [comment]
I haven't learned to use the command line tool (Git) yet, so I'm just using the Web Interface.

**Comment by captainbrosset** [comment]
Oh ok, no problem then!
It's also something I can do on my side before merging in your changes.
If you're interested (and you should be) then this seems to explain it well: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by nt1m** [comment]
@captainbrosset I did open another pull request ( #17 ) though. Thanks, I'll check the link.

**Pull request closed without merging**
